### ISSUE TITLE
@cronner-period does not actually accept all possible values for strtotime()

### ISSUE THREAD

**Issue by lucien144** [stekycz/Cronner#38]
This https://github.com/stekycz/Cronner/blob/master/Cronner/Tasks/Parser.php#L49 causes errors for strtotime acceptable values that does not start with + sign like "first day of this month" and so on...

**Comment by stekycz** [comment]
Thank you for report! What would be a solution from your point of view? I think I should update documentation only because period needs something with "+" sign.

**Comment by lucien144** [comment]
Yes, I'd update documentation and maybe the error message as well. Says that the period is not valid if actually is, is confusing :)

**Comment by stekycz** [comment]
Consider it as solved :-)
